### ISSUE TITLE
Broken file content blocking ingestion for mozilla.org

### ISSUE THREAD

**Issue by stevejalim** [mozilla/foundation-security-advisories#124]
Hi - over on Bedrock one of our ingestion scripts is unhappy, and the root cause seems to be this file and specifically the diff marker at the end. Could someone take a look, please?

https://github.com/mozilla/foundation-security-advisories/blob/76e22fdf026300782069ca30e4d2b59b77e52d75/announce/2023/mfsa2023-39.yml

**Comment by rvandermeulen** [comment]
Fixed in https://github.com/mozilla/foundation-security-advisories/commit/b6762426b8fcb51ea293b1f966dbfa0379144099
