### ISSUE TITLE
Link in recent sec advisory has restricted access

### ISSUE THREAD

**Issue by stevejalim** [mozilla/foundation-security-advisories#126]
The link below (from https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/) goes to a page which requires Google Account authentication and, presumably because I get Access Denied after authenticating with a non-Mozilla account, appropriate access to view it.

Not sure if the permissions need to change, or if it's ok to have a closed link in the sec advisory, but flagging it here for a decision. Thanks very much in advance!

https://github.com/mozilla/foundation-security-advisories/blob/2a6bbaa8cc84357ecb50a03c888d2fb0742a9878/announce/2023/mfsa2023-40.yml#L18

**Comment by tomrittervg** [comment]
This is common - Both Google and Mozilla restrict security bug details for some time to give people time to upgrade before the full details become public.
