### ISSUE TITLE
How to pair advisories to products?

### ISSUE THREAD

**Issue by graywolf** [mozilla/foundation-security-advisories#133]
What is the recommended way to find all advisories for "Firefox", or for "Firefox ESR"?

https://github.com/mozilla/foundation-security-advisories/commit/eea98a8cd6f4695193de884cf47f1a4a4eef3815#r133174122

**Comment by tomrittervg** [comment]
Hm, nothing [changed in our script](https://github.com/tomrittervg/secadv/blob/master/gen_yml.py#L206) so I wonder if this was just a one-off difference.  It's possible the people authoring the advisories this time around didn't use the script and did it manually.  @dveditz @freddyb

**Comment by mozfreddyb** [comment]
Oh. I'll fix.

**Comment by tomrittervg** [comment]
Fixed in 01a2379fb775baeb901fc878e42d3fd4b41c1ece and 9bd5833d71c6a3844083e7f9c0246f0c2cce666f

**Comment by dveditz** [comment]
> It's possible the people authoring the advisories this time around didn't use the script and did it manually. @dveditz @freddyb

Guilty: I manually created the ESR 115.5 advisory by editing the script-produced one for 120
