### ISSUE TITLE
Improve check_advisories for formatting

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/foundation-security-advisories#136]
We should add some formatting checks otherwise we wind up with issues like #135 

1. &lt;code> is not allowed in `title`
2. If a colon is present in `title`, the title must be in single quotes.
3. An HTML tag (e.g. &lt;dialog>) must not use a `<` but rather `&lt;`

It might be possible to use backticks instead of &lt;code> tags also...

**Comment by rvandermeulen** [comment]
Backticks also shouldn't be used in the `title` field.
