### ISSUE TITLE
Firefox Bug Bounty Rewards is extremely outdated

### ISSUE THREAD

**Issue by ghost** [mozilla/foundation-security-advisories#25]
Firefox Bug Bounty Rewards is extremely outdated.
https://www.mozilla.org/security/bug-bounty/hall-of-fame/

**Comment by tomrittervg** [comment]
This is also https://bugzilla.mozilla.org/show_bug.cgi?id=1517156 and will be addressed in the coming weeks.

**Comment by Anonymous123456789012** [comment]
> 
> 
> This is also https://bugzilla.mozilla.org/show_bug.cgi?id=1517156 and will be addressed in the coming weeks.

The weeks and even the months have already passed.
What is the status of update for today?

**Comment by tomrittervg** [comment]
We have a draft update; it is being reviewed before publishing.

**Comment by Anonymous123456789012** [comment]
Nice.
I'm looking forward to seeing it.
