### ISSUE TITLE
mfsa2021-41

### ISSUE THREAD

**Issue by sako9** [mozilla/foundation-security-advisories#83]
Advisory is supposed to be for Thunderbird but the fixed_in product is Firefox ESR
https://github.com/mozilla/foundation-security-advisories/blob/f280451418a0d2d7dc7cfde7bd7b6cbb6e6d1f65/announce/2021/mfsa2021-41.yml#L5

**Comment by mozfreddyb** [comment]
Gah, this is all my fault. Thanks a lot @sako9! Should be fixed now.
